### ISSUE TITLE
Exports lose 'Bundle' resourceType

### ISSUE THREAD

**Issue by awatson1978** [sync-for-science/procure-wip#17]
Great tool!  Worked great during SPHR connectathon.  One issue that came up:  the files that it exports are Bundles, but we seem to have lost the `resourceType` field.  :/

**Comment by gotdan** [comment]
Thanks for the bug report! This should be fixed now via [6ddd143](https://github.com/sync-for-science/procure-wip/commit/6ddd1431e240f7c4cede17433ade0e2d0d5b8bee).
